### ISSUE TITLE
The UI on HiDPI displays is really small.

### ISSUE THREAD

**Issue by Inferis** [SpeedyCodes/RenderBender#1]
I'm sure it must work fine on regular DPI displays, but I really have to squint here, and it's not very easy to use the controls.

![image](https://user-images.githubusercontent.com/8215/166002965-e815ebe9-5d7e-4b45-a95e-929fcb8b113a.png)

The screenshot only does so much, but the difference between the title and menu bar and the rest is obvious, I hope?

**Comment by SpeedyCodes** [comment]
I see, that does indeed look really hard to use.
I'll look into high DPI scaling, but I wouldn't really be able to test anything I write since I don't have a high DPI display myself.
Would you by any chance be willing to test this feature once it's completed?

Also, I'm sorry for my late response; most bug-reporting happens in the Minecraft RTX Discord Server, and that's where I go looking for bug reports and other RenderBender-discussions, way more often than I do here.

**Comment by SpeedyCodes** [comment]
This has been fixed in the 0.3.1 release. Thank you for reporting this issue, and testing the fixed version!
